---
- name: dotfiles | Update apt-get cache
  apt: 
    update_cache: yes

- name: dotfiles | Install base packages
  apt: 
    pkg: "{{ item }}"
    state: present
  with_items: "{{ dotfiles_base_packages }}"

- include: setup_vim.yml
- include: setup_zsh.yml
- include: setup_tmux.yml
