---

- name: dotfiles - setup_zsh | Install Oh-my-zsh
  git:
    repo: "{{ dotfiles_zsh_repo }}"
    dest: "{{ dotfiles_zsh_dir }}"
    update: yes
    accept_hostkey: yes
  become: no

- name: dotfiles - setup_zsh | Copy .zshrc
  copy: 
    remote_src: True 
    src: "{{ dotfiles_zsh_dir }}/templates/zshrc.zsh-template"
    dest: "~/.zshrc"
  become: no

- name: dotfiles - setup_zsh | Update xterm
  lineinfile:
    dest: "~/.zshrc"
    state: present
    regexp: '^export TERM=xterm'
    line: "export TERM=xterm"
  become: no

- name: dotfiles - setup_zsh | Change zsh theme
  lineinfile:
    dest: "~/.zshrc"
    state: present
    regexp: '^ZSH_THEME'
    line: 'ZSH_THEME="ys"'
  become: no

