---
- src: https://github.com/xemoe/ansible-server_preparations
  name: xemoe.server_preparations
  path: ./roles

- src: https://github.com/xemoe/ansible-dotfiles
  name: xemoe.dotfiles
  path: ./roles

- src: https://github.com/xemoe/ansible-webpack
  name: xemoe.webpack
  path: ./roles

- src: https://github.com/xemoe/ansible-apt-cacher-ng-client
  name: xemoe.apt-cacher-ng-client
  path: ./roles

- src: https://github.com/xemoe/ansible-ssh_config
  name: xemoe.ssh_config
  path: ./roles

