---
- src: JasonGiedymin.nodejs
  path: ./roles

- src: bobbyrenwick.pip
  path: ./roles

- src: ansiblebit.launchpad-ppa-webupd8
  path: ./roles

- src: ansiblebit.oracle-java
  path: ./roles

- src: geerlingguy.ruby
  path: ./roles

- src: angstwad.docker_ubuntu
  path: ./roles

