---
- name: serverspec | server_preparations
  hosts: mainbox
  gather_facts: yes
  become: yes
  roles:
    - role: 00-xemoe.server_preparations

- name: serverspec | dotfiles
  hosts: mainbox
  gather_facts: yes
  become: yes
  roles:
    - role: 10-xemoe.dotfiles

- name: serverspec | mount_sshfs
  hosts: mainbox
  gather_facts: yes
  become: yes
  roles:
    - role: 20-xemoe.mount_sshfs

