---
- name: xemoe.server_preparations
  hosts: mainbox
  gather_facts: yes
  become: yes
  vars:
    apt_proxy: 192.168.1.155:3142
  roles:
    - role: xemoe.apt-cacher-ng-client
    - role: xemoe.server_preparations
    - role: xemoe.dotfiles
    - role: xemoe.mount_sshfs

    - role: 00-xemoe.server_preparations
    - role: 10-xemoe.dotfiles
    - role: 20-xemoe.mount_sshfs
