---
- name: setup apt-cacher-ng client
  hosts: mainbox
  gather_facts: yes
  become: yes
  vars:
    apt_proxy: 192.168.1.155:3142
  roles:
    - role: xemoe.apt-cacher-ng-client

- include: roles/xemoe.server_preparations/test/main.yml
  tags: 
   - "test-server_preparations"

- include: roles/xemoe.dotfiles/test/main.yml
  tags: 
   - "test-dotfiles"

- include: roles/xemoe.webpack/test/main.yml
  tags: 
   - "test-webpack"

- include: roles/xemoe.ssh_config/test/main.yml
  tags: 
   - "test-ssh_config"

- include: roles/xemoe.mount_sshfs/test/main.yml
  tags: 
    - "test-mount_sshfs"

- include: roles/xemoe.logstash_configurations/test/test-syslog.yml
  tags: 
    - "test-logstash_configurations"

- include: roles/xemoe.logstash_configurations/test/test-files_forward.yml
  tags: 
    - "test-logstash_configurations"

