galaxy_info:
  author: Teerapong Ladlee
  description: Ansible role to prepare Ubuntu server.
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags:
    - system
    - ntp
    - apt
dependencies: []
