galaxy_info:
  author: Teerapong Ladlee
  description: Ansible role to setup dotfiles.
  license: MIT
  min_ansible_version: 2.0
  platforms:
  - name: Ubuntu
    versions:
    - xenial
  galaxy_tags:
    - vim
    - zsh
dependencies: []
